---
title: "Final Report"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

## Project title
A French Bakery’s Daily Sales in 2021-2022
<p>&nbsp;</p >


## Data collection and cleaning
[kaggle](https://www.kaggle.com/datasets/matthieugimbert/french-bakery-daily-sales)

[price comparison](https://www.france-hotel-guide.com/en/blog/cost-baguette-paris/)
<p>&nbsp;</p >

We used updated version dataset of a French bakery from 2021-01-01 to 2022-09-30. The dataset provides the daily transaction details of customers. Since the dataset is still updating, we used downloaded version on 2022-12-03.

The dataset includes:

`date`: date order

`time`: time order

`ticket number`: identifier for every single transaction

`article`: name of the product sold (in French)

`quantity`: quantity sold

`unit_price`: price per product (in Euro)

`objective`: forecast the sales in order to ease the production planning

It contains 7 variables and 234000 observations.

<p>&nbsp;</p >
Firstly, we used `read_csv()` to import the dataset "Bakery_sales.csv", and applied `janitor::clean_names()` to change the variables' names into lower cases. Next, we tidied dataset by applying `mutate()` to remove the euro sign "€", change "," to ".", convert `unit_price` to numeric form, and renamed the `article` as `product_name`. Finally, we deleted the missing data via `filter()` and `article` via `select()`. We created an `revenue` by `unit_price` * `quantity`.
<p>&nbsp;</p >

## Motivation 
It is 10:05 am in the morning, you sit in the lecture hall having your earliest lecture of the day Data Science, empty-stomached. 
A cup of coffee and a nicely warmed chocolate croissant or as French says ‘Pain Au Chocolat’ is the only thing existing in your mind… 
You wonder why the bakery items are so good and what you can do with it accompanied with the ongoing endless talking of data science 
explained by your energetic professor… Well, you jumped online and searched datasets for a French bakery and here it happens…

Bread is so much a part of French culture that even the word for “friend” comes from Latin cum pane (with bread) meaning the person 
with whom you break bread. These everyday bakery items can still be something of a mystery to people like you and me (I mean, who doesn’t 
like carbs?)

In this journey, we will take you around the analysis of a typical French bakery and find out what’s the best-seller, how much they sell, 
how is the sale distributed and so much more… 
<p>&nbsp;</p >


## Related work
<p>&nbsp;</p >

## Initial questions
<p>&nbsp;</p >

## Exploratory analyses
<p>&nbsp;</p >

## Alternative strategies/ forecast modeling
<p>&nbsp;</p >

## Descriptions of approaches
<p>&nbsp;</p >

## Discussion of results
<p>&nbsp;</p >

## Strengths and Limitations
<p>&nbsp;</p >

## Finding, Summary, and Expectation
<p>&nbsp;</p >

